
---
- include_tasks: setup-redhat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Install Docker.
  package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
  notify: restart docker


- name: 'enable docker systemd service'
  service:
    name: 'docker'
    state: 'started'
    enabled: 'yes'


- name: 'prepare default daemon configuration'
  copy:
    src: 'daemon.json'
    dest: '/etc/docker/daemon.json'


- name: 'add users to docker group'
  user:
    name: '{{ item }}'
    groups: 'docker'
    append: 'yes'
  with_items: '{{ docker_group_members }}'
  when: 'docker_group_members is defined'

- name: Create nginx container
  docker_container:
    name: "{{ container_name }}"
    image: "{{ container_image }}"
    ports: '{{ nginx_published_ports }}'
    exposed_ports: '{{ nginx_exposed_ports }}'