---

- name: install docker dependencies
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - gnupg2

- name: 'add docker repo apt key'
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: 'present'
  register: 'add_repository_key'
  ignore_errors: true


- name: add Docker repository
  apt_repository:
    repo: '{{ docker_apt_repository }}'
    state: present
    update_cache: 'yes'